apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-app-tls
  namespace: istio-system
spec:
  # Secret name where the certificate will be stored
  secretName: go-app-tls-cert
  # Use staging issuer for testing, switch to letsencrypt-prod when ready
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  # Domain names for the certificate
  dnsNames:
    - dev-k8s.phazon.app
  # Renew certificate 30 days before expiry
  renewBefore: 720h # 30 days
