apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address for ACME registration
    email: jbeeman85@hotmail.com
    # Private key secret reference
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable DNS-01 challenge provider with Cloudflare
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
          - phazon.app
