---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: '>=15.0.0 <16.0.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: ephemeral
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

    service:
      type: ClusterIP
      port: 8080

    containerPort:
      http: 8080

    # Minimal configuration for ephemeral testing
    autoscaling:
      enabled: false

    metrics:
      enabled: false
