apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: '18.x.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  targetNamespace: prod
  releaseName: example-app
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 3
    image:
      tag: "1.27.3"
    service:
      type: ClusterIP
      ports:
        http: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    podLabels:
      app: example-app
      environment: prod
      version: v1
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
