apiVersion: v1
kind: ServiceAccount
metadata:
  name: source-controller
  namespace: flux-system
  annotations:
    iam.gke.io/gcp-service-account: gke-workload-identity@ascent-wow-bot.iam.gserviceaccount.com
