apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: '1.24.x'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
      # MetalLB will assign an IP from the configured address pool
      # You can optionally specify a specific IP from your pool:
      # loadBalancerIP: 192.168.1.100
      ports:
        - name: status-port
          port: 15021
          targetPort: 15021
        - name: http2
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 443
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
    # For on-prem, typically run a single replica unless you have HA requirements
    autoscaling:
      enabled: false
    replicaCount: 1
