apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: cloudflare_api_token
    cloudflare:
      proxied: true  # Enable Cloudflare proxy (orange cloud)
    domainFilters:
      - phazon.app
    policy: sync  # Automatically sync DNS records
    sources:
      - ingress
      - istio-gateway
    txtOwnerId: gke-external-dns
    txtPrefix: "externaldns-"
