apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs
        namespace: flux-system
  values:
    # Use the latest stable external-dns version
    image:
      registry: registry.k8s.io
      repository: external-dns/external-dns
      tag: v0.19.0

    # Cloudflare provider configuration
    provider:
      name: cloudflare

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: cloudflare_api_token

    # Cloudflare-specific settings
    extraArgs:
      - --cloudflare-proxied  # Enable Cloudflare proxy (orange cloud)

    # Domain filtering
    domainFilters:
      - phazon.app

    # Sync policy: upsert-only (safer) or sync (full control)
    policy: sync

    # Sources to watch for DNS records
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice

    # Ownership settings
    txtOwnerId: gke-external-dns
    txtPrefix: "externaldns-"

    # Use existing RBAC
    serviceAccount:
      create: false
      name: external-dns

    rbac:
      create: false
