apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: '1.24.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  # Disable schema validation due to known issue with Istio gateway chart schema
  # https://github.com/istio/istio/issues/57354
  disableSchemaValidation: true
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

