# Example: Using Sealed Secrets with Flux
#
# 1. Install sealed-secrets controller:
#    kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# 2. Install kubeseal CLI:
#    brew install kubeseal
#
# 3. Create a secret and seal it:
#    echo -n 'my-secret-value' | kubectl create secret generic my-app-secret \
#      --dry-run=client \
#      --from-file=password=/dev/stdin \
#      -o yaml | \
#    kubeseal -o yaml > my-app-sealed-secret.yaml
#
# 4. Commit the sealed secret to git:
#    git add my-app-sealed-secret.yaml
#    git commit -m "Add sealed secret"
#
# 5. Reference it in your HelmRelease:

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-app-secret
  namespace: dev
spec:
  encryptedData:
    password: AgBhZ3JlYXRzZWNyZXRoZXJl...
  template:
    metadata:
      name: my-app-secret
      namespace: dev
    type: Opaque

---
# Then in your HelmRelease values:
# values:
#   env:
#     - name: DB_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: my-app-secret
#           key: password
