apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secretstore
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: "ascent-wow-bot"
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: gke-cluster-dev
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets