apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # ACME server URL for Let's Encrypt staging (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address for ACME registration
    email: your-email@example.com  # CHANGE THIS to your email
    # Private key secret reference
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: istio
