apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-secretstore
  namespace: external-dns
spec:
  provider:
    github:
      url: "https://api.github.com"
      auth:
        token:
          secretRef:
            name: github-token
            key: token
            namespace: external-secrets
