apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: go-app
      version: latest
      sourceRef:
        kind: HelmRepository
        name: go-app
        namespace: flux-system
      interval: 5m
  targetNamespace: dev
  releaseName: go-app
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 2

    image:
      repository: eminent85/go-app
      tag: latest
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    healthChecks:
      liveness:
        enabled: true
        path: /health/live
        initialDelaySeconds: 10
        periodSeconds: 10
      readiness:
        enabled: true
        path: /health/ready
        initialDelaySeconds: 5
        periodSeconds: 5
      startup:
        enabled: true
        path: /health/ready
        failureThreshold: 30
        periodSeconds: 10

    podLabels:
      app: go-app
      environment: dev
      version: v1

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      readOnlyRootFilesystem: true

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80

    podDisruptionBudget:
      enabled: true
      minAvailable: 1
