apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-service-account
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  target:
    name: gcp-service-account
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "us-west1-docker.pkg.dev": {
                "auth": "{{ .credentials | b64enc }}"
              }
            }
          }
  data:
    - secretKey: credentials
      remoteRef:
        key: GCP_SERVICE_ACCOUNT_KEY
