apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: example-app
  namespace: dev
spec:
  hosts:
    - "dev-k8s.phazon.app"
  gateways:
    - example-app-gateway
  http:
    # Route ACME challenge requests to cert-manager solver
    - match:
        - uri:
            prefix: /.well-known/acme-challenge/
      route:
        - destination:
            host: cm-acme-http-solver-7zgcq.dev.svc.cluster.local
            port:
              number: 8089
    # Route application traffic to HTTPS
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: example-app-nginx.dev.svc.cluster.local
            port:
              number: 80
          weight: 100
      timeout: 30s
      retries:
        attempts: 3
        perTryTimeout: 10s
        retryOn: gateway-error,connect-failure,refused-stream
